name: rentndeal
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#----------------------------- PACKAGES --------------------------#
dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  http: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.0
  url_launcher: ^6.1.12
  iconsax_flutter: ^1.0.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  smooth_page_indicator: ^1.1.0

  # Splash Screen
  flutter_native_splash: ^2.3.11


  # State Management
  cupertino_icons: ^1.0.6
  velocity_x: ^4.1.2
  get: ^4.6.6
  get_storage: ^2.1.1


  # Firebase Packages
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.4.0
  
  
  # Location Packages
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_places_flutter: ^2.0.8
  google_sign_in: ^6.2.1

  # Product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.0




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  adaptive_icon_background: "#000080"
  adaptive_icon_foreground: "assets/icons/launcher_icon_adaptive.png"


flutter_native_splash:
  color: "##000080"
  color_dark: "##000080"
  image: "assets/icons/launcher_icon.png"
  android: true
  ios: true

  android_12:
    color: "##000080"
    color_dark: "##000080"
    image: "assets/icons/launcher_icon.png"
    

  
flutter:

  uses-material-design: true

# To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/loginlogo/
    - lib/services/category_model.json
    - assets/images/success_email_verification.gif
    - assets/images/data_transfer.gif


  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf


    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
